package `in`.hangang.hangang.constant

const val ACCESS_TOKEN = "ACCESS_TOKEN"
const val REFRESH_TOKEN = "REFRESH_TOKEN"

const val MAIN_TIMETABLE = "MAIN_TIMETABLE"
const val TIMETABLE_LECTURE_DIPS = "TIMETABLE_LECTURE_DIPS"
const val TOGGLE_STATUS = "TOGGLE_STATUS"